---
- hosts: pi
  vars:
    homedir: /media/external
    app: hikkabot
    appdir: "{{ homedir }}/App/{{ app }}"
  tasks:
    - name: ensure app directory exists
      file:
        path: "{{ appdir }}"
        state: directory
    - name: copy binary to remote host
      copy:
        src: "../bin/{{ app }}"
        dest: "/home/ikulkov/.local/bin"
    - name: copy files to remote host
      copy:
        src: "{{ item }}"
        dest: "{{ appdir }}"
      with_items:
        - "../bin/config.yml"
        - "../bin/test.webm"
    - name: set app to executable
      file:
        path: "/home/ikulkov/.local/bin/{{ app }}"
        mode: 755
    - name: log directory exists
      file:
        path: "{{ appdir }}/log"
        state: directory

- hosts: pi
  become: yes
  vars:
    app: hikkabot
  tasks:
    - name: copy logrotate config
      copy:
        src: logrotate.conf
        dest: "/etc/logrotate.d/{{ app }}"
    - name: copy supervisor config
      copy:
        src: supervisor.conf
        dest: "/etc/supervisor/conf.d/{{ app }}.conf"
    - name: manage {{ app }} via supervisor
      supervisorctl:
        name: "{{ app }}"
        state: present
    - name: restart {{ app }}
      supervisorctl:
        name: "{{ app }}"
        state: restarted