on:
  push:
    branches: [ master ]
    tags: [ '**' ]
name: publish
jobs:
  publish:
    env:
      IMAGE_NAME: ghcr.io/jfk9w/hikkabot
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set tag
        run: |
          case $GITHUB_REF in refs/heads/master)
            TAG=latest;;
          case $GITHUB_REF in refs/tags/*)
            TAG=${GITHUB_REF#refs/tags/};;
          esac
      - name: build image
        run: |
          docker build -t ghcr.io/$GITHUB_REPOSITORY:$TAG --build-arg VERSION=$TAG .
          docker push ghcr.io/$GITHUB_REPOSITORY:$TAG
